clear variables
close all
clc

% Carrega os dados necessários
load('dados/parametrosConstrutivos.mat');

% Inicia a medição de desempenho da simulação
tic

% Simula a máquina sem excentricidade e salva 36 vetores de indutância
caracterizacaoMaquinaSaudavel

% Simula a máquina com vários níveis de excentricidade e salva 36 matrizes
% de indutância. Cada matriz contém um conjunto completo de simulações com
% amplitudes e ângulos de excentricidade variados
caracterizacaoMaquinaExcentrica

% Finaliza a medição de desempenho da simulação
tempoSimulacaoEtapa3 = toc;

% Salva todas as variáveis do espaço de trabalho
save dados/etapa3.mat

% Salva algumas variáveis específicas
save dados/indutancias.mat ...
    ampExc_tam angExc_tam angRot_tam ...
    ampExc_vetor_mm angExc_vetor_deg angRot_vetor_deg ...
    Lss11_saud_vetor Lss12_saud_vetor Lss13_saud_vetor ...
    Lss21_saud_vetor Lss22_saud_vetor Lss23_saud_vetor ...
    Lss31_saud_vetor Lss32_saud_vetor Lss33_saud_vetor ...
    Lsr11_saud_vetor Lsr12_saud_vetor Lsr13_saud_vetor ...
    Lsr21_saud_vetor Lsr22_saud_vetor Lsr23_saud_vetor ...
    Lsr31_saud_vetor Lsr32_saud_vetor Lsr33_saud_vetor ...
    Lrs11_saud_vetor Lrs12_saud_vetor Lrs13_saud_vetor ...
    Lrs21_saud_vetor Lrs22_saud_vetor Lrs23_saud_vetor ...
    Lrs31_saud_vetor Lrs32_saud_vetor Lrs33_saud_vetor ...
    Lrr11_saud_vetor Lrr12_saud_vetor Lrr13_saud_vetor ...
    Lrr21_saud_vetor Lrr22_saud_vetor Lrr23_saud_vetor ...
    Lrr31_saud_vetor Lrr32_saud_vetor Lrr33_saud_vetor ...
    Lss11_er_matriz Lss12_er_matriz Lss13_er_matriz ...
    Lss21_er_matriz Lss22_er_matriz Lss23_er_matriz ...
    Lss31_er_matriz Lss32_er_matriz Lss33_er_matriz ...
    Lsr11_er_matriz Lsr12_er_matriz Lsr13_er_matriz ...
    Lsr21_er_matriz Lsr22_er_matriz Lsr23_er_matriz ...
    Lsr31_er_matriz Lsr32_er_matriz Lsr33_er_matriz ...
    Lrs11_er_matriz Lrs12_er_matriz Lrs13_er_matriz ...
    Lrs21_er_matriz Lrs22_er_matriz Lrs23_er_matriz ...
    Lrs31_er_matriz Lrs32_er_matriz Lrs33_er_matriz ...
    Lrr11_er_matriz Lrr12_er_matriz Lrr13_er_matriz ...
    Lrr21_er_matriz Lrr22_er_matriz Lrr23_er_matriz ...
    Lrr31_er_matriz Lrr32_er_matriz Lrr33_er_matriz;